/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MAG1;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

/**
 *
 * @author Razvan
 */
public class MAGAZIN1 extends javax.swing.JFrame {
   


    /**
     * Creates new form MAGAZIN1
     */
    public MAGAZIN1() {
        initComponents();
         this.setTitle("Magazin de CD-uri");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CDdisp = new javax.swing.JButton();
        Clienti = new javax.swing.JButton();
        Cautare = new javax.swing.JButton();
        StergereClienti = new javax.swing.JButton();
        StergereCD = new javax.swing.JButton();
        Iesire = new javax.swing.JButton();
        Titlu = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        //Fundal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(500,500);
        getContentPane().setLayout(null);

        CDdisp.setText("CD-uri disponibile");
        CDdisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDdispActionPerformed(evt);
            }
        });
        getContentPane().add(CDdisp);
        CDdisp.setBounds(30, 320, 180, 50);

        Clienti.setText("Vizualizare clienti");
        Clienti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientiActionPerformed(evt);
            }
        });
        getContentPane().add(Clienti);
        Clienti.setBounds(400, 320, 180, 50);

        Cautare.setText("Adaugare client");
        Cautare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CautareActionPerformed(evt);
            }
        });
        getContentPane().add(Cautare);
        Cautare.setBounds(400, 160, 180, 50);

        Iesire.setText("Iesire");
        Iesire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IesireActionPerformed(evt);
            }
        });
        getContentPane().add(Iesire);
        Iesire.setBounds(260, 360, 90, 30);
        

        Titlu.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Titlu.setForeground(new java.awt.Color(255, 255, 255));
        Titlu.setText("Administrarea bazei de date a magazinului");
        getContentPane().add(Titlu);
        Titlu.setBounds(80, 20, 490, 70);

        jButton1.setText("Adaugare CD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 160, 180, 50);
        
        StergereCD.setText("Stergere CD");
        StergereCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StergereCDActionPerformed(evt);
            }
        });
        getContentPane().add(StergereCD);
        StergereCD.setBounds(30, 240, 180, 50);
        
        StergereClienti.setText("Stergere Client");
        StergereClienti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StergereClientiActionPerformed(evt);
            }
        });
        getContentPane().add(StergereClienti);
        StergereClienti.setBounds(400, 240, 180, 50);
        
        

        /*Fundal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MAG1/GAL00000085.jpg"))); // NOI18N
        getContentPane().add(Fundal);
        Fundal.setBounds(0, 0, 600, 420);
        */

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CDdispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDdispActionPerformed
        // TODO add your handling code here:
        CD_URI fereastra2= new CD_URI();
        fereastra2.setVisible(true);
    }//GEN-LAST:event_CDdispActionPerformed

    private void ClientiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientiActionPerformed
        // TODO add your handling code here:
        clienti fereastra1= new clienti();
        fereastra1.setVisible(true);
    }//GEN-LAST:event_ClientiActionPerformed

    private void IesireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IesireActionPerformed
        // TODO add your handling code here:
        System.exit(0);
       
    }//GEN-LAST:event_IesireActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        adaugare fereastra= new adaugare();
        fereastra.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CautareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CautareActionPerformed
        // TODO add your handling code here:
        adaugareC fereastra3= new adaugareC();
        fereastra3.setVisible(true);
    }//GEN-LAST:event_CautareActionPerformed
    
    private void StergereClientiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CautareActionPerformed
        // TODO add your handling code here:
        stergereC fereastra4= new stergereC();
        fereastra4.setVisible(true);
    }//GEN-LAST:event_CautareActionPerformed
    
    private void StergereCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CautareActionPerformed
        // TODO add your handling code here:
        stergere fereastra5= new stergere();
        fereastra5.setVisible(true);
    }//GEN-LAST:event_CautareActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAGAZIN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAGAZIN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAGAZIN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAGAZIN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         try {
        String host ="jdbc:mysql://localhost:3306/MAGAZIN_CD";
        String uName="RAZVAN";
        String Pass="dogshit";
        Connection con = DriverManager.getConnection( host, uName, Pass );
        }
        catch ( SQLException err ) {
System.out.println( err.getMessage( ) );
    }
    

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAGAZIN1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CDdisp;
    private javax.swing.JButton Cautare;
    private javax.swing.JButton Clienti;
    private javax.swing.JButton Iesire;
    private javax.swing.JLabel Titlu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton StergereCD;
    private javax.swing.JButton StergereClienti;;
    // End of variables declaration//GEN-END:variables
}
